### ISSUE TITLE
Config values storage.pgHost, pgUser and pgDatabase are ignored

### ISSUE THREAD

**Issue by ehirsch** [Haufe-Lexware/wicked.haufe.io#173]
From a look at `portal-api-deployment.yaml` it looks like you forgot something.

```yaml
{{- if .Values.storage.pgHost }}
        - name: PORTAL_STORAGE_PGHOST
          value: "{{ .Values.postgres.pgHost }}"
{{- end }}
{{- if .Values.storage.pgPort }}
        - name: PORTAL_STORAGE_PGPORT
          value: "{{ .Values.postgres.pgPort }}"
{{- end }}
{{- if .Values.storage.pgDatabase }}
        - name: PORTAL_STORAGE_PGDATABASE
          value: "{{ .Values.postgres.pgDatabase }}"
{{- end }}
```
